source_dir: "dataset"
dest_dir: "dataset_tmp"
save_dir: "save"
log_dir: "logs"
plot_dir: "plots"
target_size: !!python/tuple [256, 256]
epochs: 80
nb_folds: 8
batch_size: 16
learning_rate: 1.e-5
cores_cpu: 12
enable_checkpoint: True
enable_tensorboard: True
enable_plots: True
enable_dynamic_allocation: True
